### PR TITLE
Add rule-based auto quarantine

### PR DESCRIPTION
**Pull request by NickGrantX**
# Motivation and Context
We want a flexible mechanism for auto-quarantining messages, allowing us to create rules as necessary.

# What has changed
Added an endpoint which we can POST to, in order to create auto quarantine rules. Rules are stored in the DB so that they will survive a restart of the Exception Manager. Rules use Spring Expression Language (SpEL) to give maximum flexibility.

# How to test?
Try creating a rule by running the following CURL:
```
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"expression":"service == \"Case Processor\""}' \
  http://localhost:8666/quarantinerule
```

It's possible to use the full power of SpEL to create complicated rules. See: https://www.baeldung.com/spring-expression-language

For example, the expression to filter only receipt exceptions from Case Processor, would be:
`service == "Case Processor" and queue == "Case.Responses"`

# Links
Trello: https://trello.com/c/y2f663C6

### CODE REVIEW

**Comment by NickGrantX** [comment]
[Prototype adding some simple rules to exception manager (2 days)](https://trello.com/c/y2f663C6/940-prototype-adding-some-simple-rules-to-exception-manager-2-days)

**Review by AdamHawtin — APPROVED** [review]
👍 LGTM

**Comment by davidmort** [comment]
Looks good, do you think we'll need a method to modify/turn off rules as well?

**Comment by davidmort** [comment]
we should update the readme too, but can do that in another PR

**Review by davidmort — APPROVED** [review]

**Pull request merged**
